package com.aexp.esi.esiapi.controller;

import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class AccountLevelDTL {

    public String CM_ACCT_NO;
    public String ONE_EXPSR_CHRG_EXPSR_AM;
    public String ONE_EXPSR_LEND_EXPSR_AM;
    public String ONE_EXPSR_ACCT_AGE_BASE_DT;
    public String ONE_EXPSR_ACCT_AGE_DAY_NO;
    public String ONE_EXPSR_CURR_CD;
    public String L21AC_EVENT_TS;
    public String L21AC_LST_UPDT_TS;
    public String L21AC_LST_UPDT_USER_ID;
    public String GRMS_CUST_ID_SEQ_NO;
    public String GRMS_CUST_DB_ID_AND_CHK_DGT_NO;
    public String GRMS_CORP_ID;
    public String GRMS_CUST_CURR_CD;
    public String ACCT_CR_AVG_PAST_12_MO_AM;
    public String ACCT_HI_CR_PAST_12_MO_AM;
    public String RISK_MODEL_PROD_CD;
    public String EXT_PYMT_PLAN_ELIG_IN;
    public String ACCT_TENURE_MO_NO;
    public String GRMS_STRAT_FLAG_1_IN;
    public String GRMS_STRAT_FLAG_2_IN;
    public String GRMS_STRAT_FLAG_3_IN;
    public String GRMS_STRAT_FLAG_4_IN;
    public String GRMS_STRAT_FLAG_5_IN;
    public String GRMS_STRAT_FLAG_6_IN;
    public String GRMS_STRAT_FLAG_7_IN;
    public String GRMS_STRAT_FLAG_8_IN;
    public String ACCT_TOT_AR_EXPSR_AM;
    public String GRMS_LOG_PRCS_DT;
    public String TOT_SIGN_AND_TRVL_BAL_AM;
    public String GRMS_ACCT_DAY_AGE_NO;
    public String GRMS_BTCH_PRCS_DT;
    public String GRMS_PROD_CD;
    public String GRMS_ACCT_EFF_DT;
    public String PREV_ZIP_CD;
    public String ACCT_ZIP_CD;
    public String L2166_EVENT_TS;
    public String L2166_LST_UPDT_TS;
    public String L2166_LST_UPDT_USER_ID;
    public String GNA_ADD_DT;
    public String L21D5_EVENT_TS;
    public String L21D5_LST_UPDT_TS;
    public String L21D5_LST_UPDT_USER_ID;
    public String ACCT_ACT_IN;
    public String VIP_IN;
    public String BTA_STA_IN;
    public String EXEC_CARD_IN;
    public String GLBL_LMT_IN;
    public String SIGN_AND_TRVL_IN;
    public String LMT_LIAB_IN;
    public String TRI_MBR_IN;
    public String SYS_GEN_LOC_WARN_IN;
    public String TOT_DUE_AM;
    public String DAY_30_BAL_AM;
    public String DAY_60_BAL_AM;
    public String DAY_90_BAL_AM;
    public String L2165_EVENT_TS;
    public String L2165_LST_UPDT_TS;
    public String L2165_LST_UPDT_USER_ID;
    public String ID_OVRRD_PRG_TS;
    public String ID_OVRRD_EXPR_DT;
    public String L2184_EVENT_TS;
    public String L2184_LST_UPDT_TS;
    public String L2184_LST_UPDT_USER_ID;
    public String CR_OVRRD_PRG_DT;
    public String CR_OVRRD_ITM_ADD_VIA_CIUMC_IN;
    public String CR_OVRRD_ITM_APPL_ALL_PLAS_IN;
    public String CR_OVRRD_EXPR_DT;
    public String CR_OVRRD_REFER_AM;
    public String CR_OVRRD_SUPER_PAR_IN;
    public String CR_OVRRD_CURR_CD;
    public String CR_OVRRD_MER_TYPE_IN;
    public String L2185_EVENT_TS;
    public String L2185_LST_UPDT_TS;
    public String L2185_LST_UPDT_USER_ID;
    public String SIGN_AND_TRVL_TOT_DUE_AM;
    public String SIGN_AND_TRVL_NEW_CHRG_AM;
    public String L2195_EVENT_TS;
    public String L2195_LST_UPDT_TS;
    public String L2195_LST_UPDT_USER_ID;
    public String CR_LOSS_PRBL_NO;
    public String CR_NET_BFT_AM;
    public String TOT_STRUCT_RISK_SCORE_NO;
    public String CLNT_LVL_CR_LOSS_PRBL_NO;
    public String CLNT_FINAL_RISK_SCORE_NO;
    public String BRND_PROM_NO;
    public String MINILOG_EVENT_TS;
    public String MINILOG_LST_UPDT_TS;
    public String MINILOG_LST_UPDT_USER_ID;
    public String LOCK_IN;
    public String LOCK_TS;
    public String ACCT_12_MO_AVG_PYMT_AM;
    public String L2795_EVENT_TS;
    public String L2795_LST_UPDT_TS;
    public String L2795_LST_UPDT_USER_ID;
    public String ADJ_GBM_BUST_OUT_PRBL_SCORE_NO;
    public String ADJ_GBM_PRBL_SCORE_NO;
}
