package com.aexp.esi.esiapi.controller;

import org.springframework.jdbc.core.RowMapper;

import java.sql.ResultSet;
import java.sql.SQLException;

public class AccountLevelDTLMapper implements RowMapper<AccountLevelDTL> {

    public AccountLevelDTL mapRow(final ResultSet resultSet, final int rowNum) throws SQLException {

        return AccountLevelDTL.builder()
                .CM_ACCT_NO(resultSet.getString("CM_ACCT_NO"))
                .ONE_EXPSR_CHRG_EXPSR_AM(resultSet.getString("ONE_EXPSR_CHRG_EXPSR_AM"))
                .ONE_EXPSR_LEND_EXPSR_AM(resultSet.getString("ONE_EXPSR_LEND_EXPSR_AM"))
                .ONE_EXPSR_ACCT_AGE_BASE_DT(resultSet.getString("ONE_EXPSR_ACCT_AGE_BASE_DT"))
                .ONE_EXPSR_ACCT_AGE_DAY_NO(resultSet.getString("ONE_EXPSR_ACCT_AGE_DAY_NO"))
                .ONE_EXPSR_CURR_CD(resultSet.getString("ONE_EXPSR_CURR_CD"))
                .L21AC_EVENT_TS(resultSet.getString("L21AC_EVENT_TS"))
                .L21AC_LST_UPDT_TS(resultSet.getString("L21AC_LST_UPDT_TS"))
                .L21AC_LST_UPDT_USER_ID(resultSet.getString("L21AC_LST_UPDT_USER_ID"))
                .GRMS_CUST_ID_SEQ_NO(resultSet.getString("GRMS_CUST_ID_SEQ_NO"))
                .GRMS_CUST_DB_ID_AND_CHK_DGT_NO(resultSet.getString("GRMS_CUST_DB_ID_AND_CHK_DGT_NO"))
                .GRMS_CORP_ID(resultSet.getString("GRMS_CORP_ID"))
                .GRMS_CUST_CURR_CD(resultSet.getString("GRMS_CUST_CURR_CD"))
                .ACCT_CR_AVG_PAST_12_MO_AM(resultSet.getString("ACCT_CR_AVG_PAST_12_MO_AM"))
                .ACCT_HI_CR_PAST_12_MO_AM(resultSet.getString("ACCT_HI_CR_PAST_12_MO_AM"))
                .RISK_MODEL_PROD_CD(resultSet.getString("RISK_MODEL_PROD_CD"))
                .EXT_PYMT_PLAN_ELIG_IN(resultSet.getString("EXT_PYMT_PLAN_ELIG_IN"))
                .ACCT_TENURE_MO_NO(resultSet.getString("ACCT_TENURE_MO_NO"))
                .GRMS_STRAT_FLAG_1_IN(resultSet.getString("GRMS_STRAT_FLAG_1_IN"))
                .GRMS_STRAT_FLAG_2_IN(resultSet.getString("GRMS_STRAT_FLAG_2_IN"))
                .GRMS_STRAT_FLAG_3_IN(resultSet.getString("GRMS_STRAT_FLAG_3_IN"))
                .GRMS_STRAT_FLAG_4_IN(resultSet.getString("GRMS_STRAT_FLAG_4_IN"))
                .GRMS_STRAT_FLAG_5_IN(resultSet.getString("GRMS_STRAT_FLAG_5_IN"))
                .GRMS_STRAT_FLAG_6_IN(resultSet.getString("GRMS_STRAT_FLAG_6_IN"))
                .GRMS_STRAT_FLAG_7_IN(resultSet.getString("GRMS_STRAT_FLAG_7_IN"))
                .GRMS_STRAT_FLAG_8_IN(resultSet.getString("GRMS_STRAT_FLAG_8_IN"))
                .ACCT_TOT_AR_EXPSR_AM(resultSet.getString("ACCT_TOT_AR_EXPSR_AM"))
                .GRMS_LOG_PRCS_DT(resultSet.getString("GRMS_LOG_PRCS_DT"))
                .TOT_SIGN_AND_TRVL_BAL_AM(resultSet.getString("TOT_SIGN_AND_TRVL_BAL_AM"))
                .GRMS_ACCT_DAY_AGE_NO(resultSet.getString("GRMS_ACCT_DAY_AGE_NO"))
                .GRMS_BTCH_PRCS_DT(resultSet.getString("GRMS_BTCH_PRCS_DT"))
                .GRMS_PROD_CD(resultSet.getString("GRMS_PROD_CD"))
                .GRMS_ACCT_EFF_DT(resultSet.getString("GRMS_ACCT_EFF_DT"))
                .PREV_ZIP_CD(resultSet.getString("PREV_ZIP_CD"))
                .ACCT_ZIP_CD(resultSet.getString("ACCT_ZIP_CD"))
                .L2166_EVENT_TS(resultSet.getString("L2166_EVENT_TS"))
                .L2166_LST_UPDT_TS(resultSet.getString("L2166_LST_UPDT_TS"))
                .L2166_LST_UPDT_USER_ID(resultSet.getString("L2166_LST_UPDT_USER_ID"))
                .GNA_ADD_DT(resultSet.getString("GNA_ADD_DT"))
                .L21D5_EVENT_TS(resultSet.getString("L21D5_EVENT_TS"))
                .L21D5_LST_UPDT_TS(resultSet.getString("L21D5_LST_UPDT_TS"))
                .L21D5_LST_UPDT_USER_ID(resultSet.getString("L21D5_LST_UPDT_USER_ID"))
                .ACCT_ACT_IN(resultSet.getString("ACCT_ACT_IN"))
                .VIP_IN(resultSet.getString("VIP_IN"))
                .BTA_STA_IN(resultSet.getString("BTA_STA_IN"))
                .EXEC_CARD_IN(resultSet.getString("EXEC_CARD_IN"))
                .GLBL_LMT_IN(resultSet.getString("GLBL_LMT_IN"))
                .SIGN_AND_TRVL_IN(resultSet.getString("SIGN_AND_TRVL_IN"))
                .LMT_LIAB_IN(resultSet.getString("LMT_LIAB_IN"))
                .TRI_MBR_IN(resultSet.getString("TRI_MBR_IN"))
                .SYS_GEN_LOC_WARN_IN(resultSet.getString("SYS_GEN_LOC_WARN_IN"))
                .TOT_DUE_AM(resultSet.getString("TOT_DUE_AM"))
                .DAY_30_BAL_AM(resultSet.getString("DAY_30_BAL_AM"))
                .DAY_60_BAL_AM(resultSet.getString("DAY_60_BAL_AM"))
                .DAY_90_BAL_AM(resultSet.getString("DAY_90_BAL_AM"))
                .L2165_EVENT_TS(resultSet.getString("L2165_EVENT_TS"))
                .L2165_LST_UPDT_TS(resultSet.getString("L2165_LST_UPDT_TS"))
                .L2165_LST_UPDT_USER_ID(resultSet.getString("L2165_LST_UPDT_USER_ID"))
                .ID_OVRRD_PRG_TS(resultSet.getString("ID_OVRRD_PRG_TS"))
                .ID_OVRRD_EXPR_DT(resultSet.getString("ID_OVRRD_EXPR_DT"))
                .L2184_EVENT_TS(resultSet.getString("L2184_EVENT_TS"))
                .L2184_LST_UPDT_TS(resultSet.getString("L2184_LST_UPDT_TS"))
                .L2184_LST_UPDT_USER_ID(resultSet.getString("L2184_LST_UPDT_USER_ID"))
                .CR_OVRRD_PRG_DT(resultSet.getString("CR_OVRRD_PRG_DT"))
                .CR_OVRRD_ITM_ADD_VIA_CIUMC_IN(resultSet.getString("CR_OVRRD_ITM_ADD_VIA_CIUMC_IN"))
                .CR_OVRRD_ITM_APPL_ALL_PLAS_IN(resultSet.getString("CR_OVRRD_ITM_APPL_ALL_PLAS_IN"))
                .CR_OVRRD_EXPR_DT(resultSet.getString("CR_OVRRD_EXPR_DT"))
                .CR_OVRRD_REFER_AM(resultSet.getString("CR_OVRRD_REFER_AM"))
                .CR_OVRRD_SUPER_PAR_IN(resultSet.getString("CR_OVRRD_SUPER_PAR_IN"))
                .CR_OVRRD_CURR_CD(resultSet.getString("CR_OVRRD_CURR_CD"))
                .CR_OVRRD_MER_TYPE_IN(resultSet.getString("CR_OVRRD_MER_TYPE_IN"))
                .L2185_EVENT_TS(resultSet.getString("L2185_EVENT_TS"))
                .L2185_LST_UPDT_TS(resultSet.getString("L2185_LST_UPDT_TS"))
                .L2185_LST_UPDT_USER_ID(resultSet.getString("L2185_LST_UPDT_USER_ID"))
                .SIGN_AND_TRVL_TOT_DUE_AM(resultSet.getString("SIGN_AND_TRVL_TOT_DUE_AM"))
                .SIGN_AND_TRVL_NEW_CHRG_AM(resultSet.getString("SIGN_AND_TRVL_NEW_CHRG_AM"))
                .L2195_EVENT_TS(resultSet.getString("L2195_EVENT_TS"))
                .L2195_LST_UPDT_TS(resultSet.getString("L2195_LST_UPDT_TS"))
                .L2195_LST_UPDT_USER_ID(resultSet.getString("L2195_LST_UPDT_USER_ID"))
                .CR_LOSS_PRBL_NO(resultSet.getString("CR_LOSS_PRBL_NO"))
                .CR_NET_BFT_AM(resultSet.getString("CR_NET_BFT_AM"))
                .TOT_STRUCT_RISK_SCORE_NO(resultSet.getString("TOT_STRUCT_RISK_SCORE_NO"))
                .CLNT_LVL_CR_LOSS_PRBL_NO(resultSet.getString("CLNT_LVL_CR_LOSS_PRBL_NO"))
                .CLNT_FINAL_RISK_SCORE_NO(resultSet.getString("CLNT_FINAL_RISK_SCORE_NO"))
                .BRND_PROM_NO(resultSet.getString("BRND_PROM_NO"))
                .MINILOG_EVENT_TS(resultSet.getString("MINILOG_EVENT_TS"))
                .MINILOG_LST_UPDT_TS(resultSet.getString("MINILOG_LST_UPDT_TS"))
                .MINILOG_LST_UPDT_USER_ID(resultSet.getString("MINILOG_LST_UPDT_USER_ID"))
                .LOCK_IN(resultSet.getString("LOCK_IN"))
                .LOCK_TS(resultSet.getString("LOCK_TS"))
                .ACCT_12_MO_AVG_PYMT_AM(resultSet.getString("ACCT_12_MO_AVG_PYMT_AM"))
                .L2795_EVENT_TS(resultSet.getString("L2795_EVENT_TS"))
                .L2795_LST_UPDT_TS(resultSet.getString("L2795_LST_UPDT_TS"))
                .L2795_LST_UPDT_USER_ID(resultSet.getString("L2795_LST_UPDT_USER_ID"))
                .ADJ_GBM_BUST_OUT_PRBL_SCORE_NO(resultSet.getString("ADJ_GBM_BUST_OUT_PRBL_SCORE_NO"))
                .ADJ_GBM_PRBL_SCORE_NO(resultSet.getString("ADJ_GBM_PRBL_SCORE_NO"))
                .build();


    }
}
