package com.aexp.esi.esiapi.controller;

import org.springframework.jdbc.core.RowMapper;

import java.sql.ResultSet;
import java.sql.SQLException;

public class Mer_DTLMapper implements RowMapper<Mer_DTL> {

    public Mer_DTL mapRow(final ResultSet resultSet, final int rowNum) throws SQLException {

        return Mer_DTL.builder()
                .MER_SE_NO(resultSet.getString("MER_SE_NO"))
                .SE_PRV_NOT_VIST_RCNT_FRD_GR_RT(resultSet.getString("SE_PRV_NOT_VIST_RCNT_FRD_GR_RT"))
                .SE_PRV_VIST_RCNT_FRD_GR_RT(resultSet.getString("SE_PRV_VIST_RCNT_FRD_GR_RT"))
                .SE_PRV_NOT_VIST_FRD_TO_GR_RT(resultSet.getString("SE_PRV_NOT_VIST_FRD_TO_GR_RT"))
                .SE_PRV_VIST_FRD_TO_GR_RT(resultSet.getString("SE_PRV_VIST_FRD_TO_GR_RT"))
                .TRK1_MISS_CHRG_RCNT_FRD_GR_RT(resultSet.getString("TRK1_MISS_CHRG_RCNT_FRD_GR_RT"))
                .AAV_RTRN_CD_RCNT_FRD_GR_RT(resultSet.getString("AAV_RTRN_CD_RCNT_FRD_GR_RT"))
                .EMAIL_MSMTCH_RCNT_FRD_GR_RT(resultSet.getString("EMAIL_MSMTCH_RCNT_FRD_GR_RT"))
                .SIMPLE_SE_FRD_TO_GR_RT(resultSet.getString("SIMPLE_SE_FRD_TO_GR_RT"))
                .FRD_TO_GR_AM(resultSet.getString("FRD_TO_GR_AM"))
                .CM_GRMS_CURR_CD(resultSet.getString("CM_GRMS_CURR_CD"))
                .CUST_SEQ_NO(resultSet.getString("CUST_SEQ_NO"))
                .QLFY_DB_ID_AND_CHK_DGT_NO(resultSet.getString("QLFY_DB_ID_AND_CHK_DGT_NO"))
                .SE_NM(resultSet.getString("SE_NM"))
                .SE_SAME_AM_DEN_NO(resultSet.getString("SE_SAME_AM_DEN_NO"))
                .AFFL_SE_1_NO(resultSet.getString("AFFL_SE_1_NO"))
                .AFFL_SE_2_NO(resultSet.getString("AFFL_SE_2_NO"))
                .AFFL_SE_3_NO(resultSet.getString("AFFL_SE_3_NO"))
                .CENT_AUTH_US_OIL_SE_IN(resultSet.getString("CENT_AUTH_US_OIL_SE_IN"))
                .INET_SE_IN(resultSet.getString("INET_SE_IN"))
                .HI_RISK_OIL_SE_CTGY_1_IN(resultSet.getString("HI_RISK_OIL_SE_CTGY_1_IN"))
                .HI_RISK_OIL_SE_CTGY_2_IN(resultSet.getString("HI_RISK_OIL_SE_CTGY_2_IN"))
                .HI_RISK_OIL_SE_CTGY_4_IN(resultSet.getString("HI_RISK_OIL_SE_CTGY_4_IN"))
                .AGGR_SE_CTGY_1_CD(resultSet.getString("AGGR_SE_CTGY_1_CD"))
                .AGGR_SE_CTGY_2_CD(resultSet.getString("AGGR_SE_CTGY_2_CD"))
                .SE_TYPE_IN(resultSet.getString("SE_TYPE_IN"))
                .SE_TYPE_OVRRD_IN(resultSet.getString("SE_TYPE_OVRRD_IN"))
                .SE_CTRY_CD(resultSet.getString("SE_CTRY_CD"))
                .WORLDWIDE_INDUS_CD(resultSet.getString("WORLDWIDE_INDUS_CD"))
                .SE_STRATERGY_FLAG_1_IN(resultSet.getString("SE_STRATERGY_FLAG_1_IN"))
                .SE_STRATERGY_FLAG_2_IN(resultSet.getString("SE_STRATERGY_FLAG_2_IN"))
                .SE_STRATERGY_FLAG_3_IN(resultSet.getString("SE_STRATERGY_FLAG_3_IN"))
                .SE_STRATERGY_FLAG_4_IN(resultSet.getString("SE_STRATERGY_FLAG_4_IN"))
                .SE_TENURE_IN_MO_NO(resultSet.getString("SE_TENURE_IN_MO_NO"))
                .SE_MO_AVG_VOL_AM(resultSet.getString("SE_MO_AVG_VOL_AM"))
                .SE_AVG_CHRG_REQ_CR_AM(resultSet.getString("SE_AVG_CHRG_REQ_CR_AM"))
                .SE_SIMPLE_MO_AVG_VOL_AM(resultSet.getString("SE_SIMPLE_MO_AVG_VOL_AM"))
                .STA_CD(resultSet.getString("STA_CD"))
                .SE_RISK_STA_CD(resultSet.getString("SE_RISK_STA_CD"))
                .SE_STA_CD(resultSet.getString("SE_STA_CD"))
                .SE_CURR_CD(resultSet.getString("SE_CURR_CD"))
                .MER_CTGY_CD(resultSet.getString("MER_CTGY_CD"))
                .SE_ALPHA_GRP_TYPE_CD(resultSet.getString("SE_ALPHA_GRP_TYPE_CD"))
                .SE_TYPE_OVRRD_CD(resultSet.getString("SE_TYPE_OVRRD_CD"))
                .OPEN_DT(resultSet.getString("OPEN_DT"))
                .SE_MBR_RELAVENT_NM(resultSet.getString("SE_MBR_RELAVENT_NM"))
                .CITY_NM(resultSet.getString("CITY_NM"))
                .STATE_NM(resultSet.getString("STATE_NM"))
                .CTRY_CD(resultSet.getString("CTRY_CD"))
                .METRO_CITY_CD(resultSet.getString("METRO_CITY_CD"))
                .HI_RISK_ZIP_SEG_IN(resultSet.getString("HI_RISK_ZIP_SEG_IN"))
                .BAD_LOCAT_SE_IN(resultSet.getString("BAD_LOCAT_SE_IN"))
                .AGGR_CTGY_3(resultSet.getString("AGGR_CTGY_3"))
                .AGGR_CTGY_4(resultSet.getString("AGGR_CTGY_4"))
                .HI_RISK_OIL_SE_CTGY_3(resultSet.getString("HI_RISK_OIL_SE_CTGY_3"))
                .ONLN_PYMT_CD(resultSet.getString("ONLN_PYMT_CD"))
                .AFFL_TYPE_1_CD(resultSet.getString("AFFL_TYPE_1_CD"))
                .AFFL_TYPE_2_CD(resultSet.getString("AFFL_TYPE_2_CD"))
                .AFFL_TYPE_3_CD(resultSet.getString("AFFL_TYPE_3_CD"))
                .MER_ZIP_CD(resultSet.getString("MER_ZIP_CD"))
                .SE_NON_DEROG_CANC_RSN_CD(resultSet.getString("SE_NON_DEROG_CANC_RSN_CD"))
                .CR_TO_GR_RT(resultSet.getString("CR_TO_GR_RT"))
                .SE_KEY_PCT_RT(resultSet.getString("SE_KEY_PCT_RT"))
                .RISK_TOC_NO(resultSet.getString("RISK_TOC_NO"))
                .SE_TRANSACTING_CTRY_CD(resultSet.getString("SE_TRANSACTING_CTRY_CD"))
                .THIRD_PTY_AGGR_IN(resultSet.getString("THIRD_PTY_AGGR_IN"))
                .L4150_EVENT_TS(resultSet.getString("L4150_EVENT_TS"))
                .L4150_LST_UPDT_TS(resultSet.getString("L4150_LST_UPDT_TS"))
                .L4150_LST_UPDT_USER_ID(resultSet.getString("L4150_LST_UPDT_USER_ID"))
                .SE_LST_PEND_DENY_TS(resultSet.getString("SE_LST_PEND_DENY_TS"))
                .TRANS_AM(resultSet.getString("TRANS_AM"))
                .MOST_RCNT_TRANS_IN(resultSet.getString("MOST_RCNT_TRANS_IN"))
                .TRANSACTING_CM_NM(resultSet.getString("TRANSACTING_CM_NM"))
                .SE_TOT_TRANS_CT(resultSet.getString("SE_TOT_TRANS_CT"))
                .SE_TOT_UNIQUE_CUST_CT(resultSet.getString("SE_TOT_UNIQUE_CUST_CT"))
                .SE_FRD_CHRG_UNIQUE_CUST_CT(resultSet.getString("SE_FRD_CHRG_UNIQUE_CUST_CT"))
                .MINILOG_EVENT_TS(resultSet.getString("MINILOG_EVENT_TS"))
                .MINILOG_LST_UPDT_TS(resultSet.getString("MINILOG_LST_UPDT_TS"))
                .MINILOG_LST_UPDT_USER_ID(resultSet.getString("MINILOG_LST_UPDT_USER_ID"))

        .build();
    }
}
